version: '2'

services:

    zero_mvc:
        image: zero/mvc
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        ports:
            - "9903:80"
        volumes:
            - "./Mvc-Logs:/app/App_Data/Logs"